### ISSUE TITLE
关于506、507行注释的疑惑 

### ISSUE THREAD

**Issue by roy-lau** [qq281113270/vue#21]
https://github.com/qq281113270/vue/blob/4d5cb90f4cce3f74e736335cad46e929f4e0c202/vue.js#L506-L507

您是不是把第 506、507 行里的 **view** 拼写成 **wiew** 了？还是我英语太差没有学过 wiew 这个单词？如果不是拼写错误 ，还请解释下 wiew 这个单词的含义，谢谢！

**Comment by qq281113270** [comment]
抱歉单词写错了

**Comment by roy-lau** [comment]
> 抱歉单词写错了

那就让我混大佬给 pr 吧！#22

**Comment by ygs-code** [comment]
@roy-lau   感谢支持，我更新文档了
